# Generated by Django 5.1.2 on 2024-10-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_habilidades_alter_persona_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='habilidades',
            field=models.ManyToManyField(to='empleados.habilidades'),
        ),
    ]
