# Generated by Django 5.1.2 on 2024-10-25 01:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_persona_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hojavida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
    ]
