# Generated by Django 5.1.2 on 2024-10-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_persona_hojavida'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombres Completos'),
        ),
    ]
